apiVersion: v1
kind: Service
metadata:
  name: tracks
  labels:
    app: tracks
spec:
  selector:
    app: tracks
  ports:
  - port: 4567

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tracks
  labels:
    app: tracks
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: tracks
    spec:
      containers:
      - name: tracks
        image: christopherhein/mx-tracks
        # resources:
        #   limits:
        #     cpu: 1024m
        #     memory: 1024M
        #   requests:
        #     cpu: 512m
        #     memory: 512M
        ports:
        - containerPort: 4567
