apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: http-server
    name: http
  - port: 443
    targetPort: http-server
    name: ssl
  type: LoadBalancer

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: christopherhein/mx-webapp
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: TRACKS_HOST
          value: tracks
        - name: TRACKS_PORT
          value: "4567"
        - name: LAPTIMES_HOST
          value: laptimes
        - name: LAPTIMES_PORT
          value: "5000"

